services:
  next:
    build: ./my-next-app
    depends_on:
      - express
    environment:
      PORT: 3000
      NODE_ENV: "development"

    networks: 
      - ip6net
    ports:
      - "3000:3000"
    
    restart: always
    volumes:
      - ./my-next-app/:/app
      - /app/node_modules
      - /app/.next
  
  express:
    build: ./express
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - DEBUG=app:*
      - PORT=8080

    networks: 
    - ip6net
    ports:
      - "8080:8080"

  mongo:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    networks: 
      - ip6net
    ports:
      - "27017:27017"

volumes:
  db-data:

networks:
  ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 2001:db8::/64

